### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by 408550969** [yihui-he/caffe-pro#1]
Caffe reported the following error:
src/caffe/test/test_filter_layer.cpp: In instantiation of ‘caffe::FilterLayerTest<TypeParam>::FilterLayerTest() [with TypeParam = caffe::GPUDevice<double>]’:
src/caffe/test/test_filter_layer.cpp:106:1:   required from ‘testing::Test* testing::internal::TestFactoryImpl<TestClass>::CreateTest() [with TestClass = caffe::FilterLayerTest_TestGradient_Test<caffe::GPUDevice<double> >]’
src/caffe/test/test_filter_layer.cpp:117:1:   required from here
src/caffe/test/test_filter_layer.cpp:20:3: error: uninitialized const member in ‘class caffe::Blob<double>* const’ [-fpermissive]
   FilterLayerTest()
   ^
src/caffe/test/test_filter_layer.cpp:47:22: note: ‘caffe::Blob<double>* const caffe::FilterLayerTest<caffe::GPUDevice<double> >::blob_bottom_labels_’ should be initialized
   Blob<Dtype>* const blob_bottom_labels_;
                      ^
src/caffe/test/test_filter_layer.cpp:20:3: error: uninitialized const member in ‘class caffe::Blob<double>* const’ [-fpermissive]
   FilterLayerTest()
   ^
src/caffe/test/test_filter_layer.cpp:48:22: note: ‘caffe::Blob<double>* const caffe::FilterLayerTest<caffe::GPUDevice<double> >::blob_bottom_selector_’ should be initialized
   Blob<Dtype>* const blob_bottom_selector_;
                      ^
src/caffe/test/test_filter_layer.cpp:20:3: error: uninitialized const member in ‘class caffe::Blob<double>* const’ [-fpermissive]
   FilterLayerTest()
   ^
src/caffe/test/test_filter_layer.cpp:51:22: note: ‘caffe::Blob<double>* const caffe::FilterLayerTest<caffe::GPUDevice<double> >::blob_top_labels_’ should be initialized
   Blob<Dtype>* const blob_top_labels_;
                      ^
src/caffe/test/test_filter_layer.cpp: In instantiation of ‘caffe::FilterLayerTest<TypeParam>::FilterLayerTest() [with TypeParam = caffe::GPUDevice<float>]’:
src/caffe/test/test_filter_layer.cpp:106:1:   required from ‘testing::Test* testing::internal::TestFactoryImpl<TestClass>::CreateTest() [with TestClass = caffe::FilterLayerTest_TestGradient_Test<caffe::GPUDevice<float> >]’
src/caffe/test/test_filter_layer.cpp:117:1:   required from here
src/caffe/test/test_filter_layer.cpp:20:3: error: uninitialized const member in ‘class caffe::Blob<float>* const’ [-fpermissive]
   FilterLayerTest()
   ^
src/caffe/test/test_filter_layer.cpp:47:22: note: ‘caffe::Blob<float>* const caffe::FilterLayerTest<caffe::GPUDevice<float> >::blob_bottom_labels_’ should be initialized
   Blob<Dtype>* const blob_bottom_labels_;
                      ^
src/caffe/test/test_filter_layer.cpp:20:3: error: uninitialized const member in ‘class caffe::Blob<float>* const’ [-fpermissive]
   FilterLayerTest()
   ^
src/caffe/test/test_filter_layer.cpp:48:22: note: ‘caffe::Blob<float>* const caffe::FilterLayerTest<caffe::GPUDevice<float> >::blob_bottom_selector_’ should be initialized
   Blob<Dtype>* const blob_bottom_selector_;
                      ^
src/caffe/test/test_filter_layer.cpp:20:3: error: uninitialized const member in ‘class caffe::Blob<float>* const’ [-fpermissive]
   FilterLayerTest()
   ^
src/caffe/test/test_filter_layer.cpp:51:22: note: ‘caffe::Blob<float>* const caffe::FilterLayerTest<caffe::GPUDevice<float> >::blob_top_labels_’ should be initialized
   Blob<Dtype>* const blob_top_labels_;
                      ^
src/caffe/test/test_filter_layer.cpp: In instantiation of ‘caffe::FilterLayerTest<TypeParam>::FilterLayerTest() [with TypeParam = caffe::CPUDevice<double>]’:
src/caffe/test/test_filter_layer.cpp:106:1:   required from ‘testing::Test* testing::internal::TestFactoryImpl<TestClass>::CreateTest() [with TestClass = caffe::FilterLayerTest_TestGradient_Test<caffe::CPUDevice<double> >]’
src/caffe/test/test_filter_layer.cpp:117:1:   required from here
src/caffe/test/test_filter_layer.cpp:20:3: error: uninitialized const member in ‘class caffe::Blob<double>* const’ [-fpermissive]
   FilterLayerTest()
   ^
src/caffe/test/test_filter_layer.cpp:47:22: note: ‘caffe::Blob<double>* const caffe::FilterLayerTest<caffe::CPUDevice<double> >::blob_bottom_labels_’ should be initialized
   Blob<Dtype>* const blob_bottom_labels_;
                      ^
src/caffe/test/test_filter_layer.cpp:20:3: error: uninitialized const member in ‘class caffe::Blob<double>* const’ [-fpermissive]
   FilterLayerTest()
   ^
src/caffe/test/test_filter_layer.cpp:48:22: note: ‘caffe::Blob<double>* const caffe::FilterLayerTest<caffe::CPUDevice<double> >::blob_bottom_selector_’ should be initialized
   Blob<Dtype>* const blob_bottom_selector_;
                      ^
src/caffe/test/test_filter_layer.cpp:20:3: error: uninitialized const member in ‘class caffe::Blob<double>* const’ [-fpermissive]
   FilterLayerTest()
   ^
src/caffe/test/test_filter_layer.cpp:51:22: note: ‘caffe::Blob<double>* const caffe::FilterLayerTest<caffe::CPUDevice<double> >::blob_top_labels_’ should be initialized
   Blob<Dtype>* const blob_top_labels_;
                      ^
src/caffe/test/test_filter_layer.cpp: In instantiation of ‘caffe::FilterLayerTest<TypeParam>::FilterLayerTest() [with TypeParam = caffe::CPUDevice<float>]’:
src/caffe/test/test_filter_layer.cpp:106:1:   required from ‘testing::Test* testing::internal::TestFactoryImpl<TestClass>::CreateTest() [with TestClass = caffe::FilterLayerTest_TestGradient_Test<caffe::CPUDevice<float> >]’
src/caffe/test/test_filter_layer.cpp:117:1:   required from here
src/caffe/test/test_filter_layer.cpp:20:3: error: uninitialized const member in ‘class caffe::Blob<float>* const’ [-fpermissive]
   FilterLayerTest()
   ^
src/caffe/test/test_filter_layer.cpp:47:22: note: ‘caffe::Blob<float>* const caffe::FilterLayerTest<caffe::CPUDevice<float> >::blob_bottom_labels_’ should be initialized
   Blob<Dtype>* const blob_bottom_labels_;
                      ^
src/caffe/test/test_filter_layer.cpp:20:3: error: uninitialized const member in ‘class caffe::Blob<float>* const’ [-fpermissive]
   FilterLayerTest()
   ^
src/caffe/test/test_filter_layer.cpp:48:22: note: ‘caffe::Blob<float>* const caffe::FilterLayerTest<caffe::CPUDevice<float> >::blob_bottom_selector_’ should be initialized
   Blob<Dtype>* const blob_bottom_selector_;
                      ^
src/caffe/test/test_filter_layer.cpp:20:3: error: uninitialized const member in ‘class caffe::Blob<float>* const’ [-fpermissive]
   FilterLayerTest()
   ^
src/caffe/test/test_filter_layer.cpp:51:22: note: ‘caffe::Blob<float>* const caffe::FilterLayerTest<caffe::CPUDevice<float> >::blob_top_labels_’ should be initialized
   Blob<Dtype>* const blob_top_labels_;
                      ^
Makefile:582: recipe for target '.build_release/src/caffe/test/test_filter_layer.o' failed
make: *** [.build_release/src/caffe/test/test_filter_layer.o] Error 1

**Comment by 408550969** [comment]
Is it because the filter_layer.cpp is empty? 
And I have 5 runtest error:
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] MatmulLayerTest/0.TestGradient, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] ConvolutionLayerTest/2.TestSimpleConvolutionGroup, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] ConvolutionLayerTest/2.TestGradientGroup, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] ConvolutionLayerTest/3.TestSimpleConvolutionGroup, where TypeParam = caffe::GPUDevice<double>
[  FAILED  ] ConvolutionLayerTest/3.TestGradientGroup, where TypeParam = caffe::GPUDevice<double>
Is that all right?

**Comment by ethanhe42** [comment]
you don't need to make test
